travis:
  secure:
    BINSTAR_TOKEN: XOPBadFYD9w2u+4ImgFEy1ujGqWth+kTpHz2hxit6uYljkklncJZtUfa/DmW0+YsDUHWBM/LBM1fBFY8sBr8A0zSq/RmgCtGYFwcHE/vuXy0ZkWq9gQZ4YHkamZusrnLVdR1YpkUq7u9hbBWqqVJSlzogDmgzRSskqksu7s4ndXDGNhsOSBRM+jBVewv/kjKeeEYpPMY2QKOp8kJmacN1rYPZTG3enTdhSx15tLF8ExGmmTGvgc0PfXXmArelrSngmpV3g1Sh7sHGu2altBS6O5JM/3MlYrWSjNhi0RfLRnzsR4cj+goYXXS4HSe92gQ07AaCRCgQ87i91WT3ANgeVfe651/1h37Vfz/NXP+psx48l/nCgRlkoRgWEWztIk8JVwXCSkGahg2ty8nw8aulhc61g2iOb/M3+wMHxv0tJZyIwRZvXL95z7VeTkIGf4CdjbNoQ6MFohol/OEUl6ov17f6FBAgwkjZ0ddXpZ2/GbB5p2OJNHT1oHxME13Reg6Ko6XBEGM06mVQAZk8XRT80YEjW5d5oMt9AftWt8LRbtrXrTrGxd0OWxB9qBmcFEicT50UZ0wVA2b5ixW3EaLvTH0GNJRoiwMD7i+yQJHTc0/LAJeVhfDhha56p+q3TScrAo64U8AtskMVS0VR3F6EZ7A0Tx1DSIscLSmZApWTxU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
